repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
          - --exclude-files
          - '^(data/|agentic-copilot/data/|.*\.(png|jpg|jpeg|gif|tps|uasset|umap|exe|dll|bin|pak|pdb))$'
