services:
  qdrant:
    image: qdrant/qdrant:v1.15.5     # pin version
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    # healthcheck:                       # optional (only if the image has curl or wget)
    #   test: ["CMD-SHELL", "wget -qO- http://localhost:6333/readyz || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10

  app:
    build: ./app
    depends_on:
      - qdrant                         # waits for container start (not health)
    env_file:
      - ./.env
    volumes:
      # your corpora (read-only)
      - ./data/unreal_docs:/ingest/unreal_docs:ro
      - ./data/project:/ingest/project:ro
      - ./data/plugins:/ingest/plugins:ro
      # cache model downloads between runs (big speedup after first pull)
      - hf_cache:/root/.cache/huggingface
      # - torch_cache:/root/.cache/torch     # uncomment if you see torch downloads
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    # tty: true           # optional (Windows dev QoL)
    # stdin_open: true

volumes:
  qdrant_storage:
  hf_cache:
  # torch_cache:
