version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.15.5
    ports:
      - "6333:6333"
      - "6334:6334"
    # Use a named volume to avoid Windows bind-mount warnings and improve stability
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      QDRANT_URL: http://qdrant:6333
      BACKEND_CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./ingest:/app/ingest:ro
      - ./out:/app/out
    depends_on:
      - qdrant
    ports:
      - "8080:8080"
    # Ensure the backend runs a long-lived HTTP server
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8080
      --proxy-headers
      --forwarded-allow-ips="*"
    # Simple healthcheck using Python (available in the image)
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8080/health', timeout=2).getcode()==200 else sys.exit(1)"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: devcopilot-web
    ports:
      - "3000:3000"
    # Wait for backend to be healthy before starting the web app (Compose spec supports this)
    depends_on:
      app:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_BASE: http://localhost:8080
    restart: unless-stopped

volumes:
  qdrant_storage: