version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: ./app
    depends_on: [qdrant]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=bge-small-en
    volumes:
      - ./data/unreal_docs:/ingest/unreal_docs:ro
      - ./data/project:/ingest/project:ro
      - ./data/plugins:/ingest/plugins:ro
    command: ["python", "-m", "src.main"]
    ports: ["8080:8080"]

volumes:
  qdrant_storage:
